justintime/account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = "account"
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/login.html'), name='user_login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='account/logout.html'), name='user_logout'),
    path('register/', views.register, name='user_register'),
    path('contact/', views.contact, name='contact'),
    path('my-information/', views.myself, name='my_information'),
    path('edit-my-information/', views.myself_edit, name="edit_my_information"),
    path('my-image/', views.my_image, name='my_image'),
    path('my-orders/', views.my_orders, name='my_orders')

]

justintime/hotel/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = "hotel"
urlpatterns = [
    #path('contact/', views.contact, name='contact'),
    path('', views.hotelsearch, name='search'),
    path("booking/<city>/<name>", views.booking, name="booking"),
    path("book/<int:room_id>", views.book, name="book"),
    path('cancel/<int:room_id>', views.cancel, name='cancel'),
]

justintime/justintime/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name="index.html"),name='index'),
    path('account/', include('account.urls', namespace='account')),
    path('hotel/', include('hotel.urls', namespace='hotel')),
    path('flight/', include('flight.urls', namespace='flight')),
]

justintime/templates/base.html
<!doctype html>
{% load static %}

<html>
<head>
    <meta charset="utf-8">
    <title> JustInTime</title>
  
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    
    <link rel="stylesheet" herf="{%  static 'css/bootstrap/bootstrap.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    <link href="https://fonts.googleapis.com/css?family=Indie+Flower|Solway|Tomorrow&display=swap" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

    {% if title %}
        <title>Django Blog - {{ title }}</title>
    {% else %}
        <title>Just In Time</title>
    {% endif %}
    <style>
        .img-circle {
          border-radius: 50%;
        }
    </style>

</head>

          
<body >  
    <nav class="signin-navbar">
        <ul>

            {% if user.is_authenticated %}
                <li><a href="{% url 'account:my_information' %}">{{  user.username }}</a></li>
                <li><a href="{% url 'account:my_orders' %}">Orders</a></li>

                <li><a href="{% url 'account:user_logout' %}">Logout</a></li>

            {% else %}
                <li><a href="{% url 'account:user_login' %}">Login</a></li>
                <li><a href="{% url 'account:user_register' %}">Register</a></li>
            {% endif %}
            <li><a href="{% url 'account:contact' %}">Contact Us</a></li>
        </ul>
    </nav>

    <header class="tm-header">
            <img class="tm-logo" src= "{% static 'images/logo.png'%}" alt="JustInTime">
    
            <nav class="tm-nav" >
                <div class="container-fluid">
                <ul>
                    <li><a class="active" href="{% url 'index' %}">Home</a></li>
                    <li><a href="{% url 'flight:search' %}">Flight </a></li>
                    <li><a href="{% url 'hotel:search' %}">Hotel</a></li>
                </ul>  
                </div>  
            </nav>


    </header>

   
        {% block content %}
        
        {% endblock %}
    
  
         <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="../static/js/vendor/jquery-1.11.2.min.js"><\/script>')</script>

        <script src="{%static 'js/vendor/bootstrap.min.js' %}"></script>

        <script src="{%static 'js/main.js' %}"></script>
</body>
</html>

justintime/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}

    {% if user.is_authenticated %}
        <h2 class="hello">Hello User: {{ user.username }}</h2>
   
    {% endif %}
 
<h2><center> Where do you want to visit?</center></h2>
     
     <section class="slider room flex">

      
                    <div class="tm-place">
                        <img  src= "{% static 'images/rocky.jpeg' %}">
                       <a href="{% url 'flight:search' %}"> <p class="s">Rocky Mountain</p> </a>

                    </div>
                        <div class="tm-place">
                        <img  src= "{% static 'images/zion.jpeg' %}">
                            <a href="{% url 'flight:search' %}"> <p class="s">Zion National Park</p></a>

                    </div>
                        <div class="tm-place">
                        <img  src= "{% static 'images/gc.jpeg' %}">
                            <a href="{% url 'flight:search' %}">  <p class="s">Grand Canyon</p></a>

                    </div>
                    </div>
                        <div class="tm-place">
                        <img  src= "{% static 'images/yellow.jpg' %}">
                        <a href="{% url 'flight:search' %}">  <p class="s">Yellowstone</p></a>

                    </div>
                
    </section>

    <h2><center>Where do you want to stay?</center></h2>
     
     <section class="slider room flex">

      
                    <div class="tm-place">
                        <img  src= "{% static 'images/classic.jpg' %}">
                       <a href="{% url 'hotel:search' %}"> <p class="s">Classic Hotel</p> </a>

                    </div>
                        <div class="tm-place">
                       <!--  <img  src="images/davison.jpg"> -->
                       <img  src= "{% static 'images/davison.jpg' %}">
                            <a href="{% url 'hotel:search' %}"> <p class="s">Davision Hotel</p></a>

                    </div>
                        <div class="tm-place">
                        <img  src= "{% static 'images/hardrock.jpg' %}">
                            <a href="{% url 'hotel:search' %}">  <p class="s">HardRock Hotel</p></a>

                    </div>
                    </div>
                        <div class="tm-place">
                        <img  src= "{% static 'images/hilton.jpg' %}">
                        <a href="{% url 'hotel:search' %}">  <p class="s">Hilton Hotel</p></a>

                    </div>
               
    </section>

{% endblock %}